/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DrawerAlarmas: typeof import('./src/components/drawerAlarmas.vue')['default']
    EstadisticasOrdenes: typeof import('./src/components/EstadisticasOrdenes.vue')['default']
    EstadoChip: typeof import('./src/components/EstadoChip.vue')['default']
    Filtro: typeof import('./src/components/Filtro.vue')['default']
    GraficosDetalles: typeof import('./src/components/GraficosDetalles.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TablaAlarmas: typeof import('./src/components/TablaAlarmas.vue')['default']
    TablaOrdenes: typeof import('./src/components/TablaOrdenes.vue')['default']
  }
}
